import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { load, payFlagApuntarse, payFlagCasino } from '../functions/functions';
import React, { useState, useEffect } from 'react';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [refresh, setRefresh] = useState(true);

  const payFlag1 = async () => {

    const { address, provider, payment_system_apuntarse, payment_system_casino } = await load();
   
    let hash = await payFlagApuntarse( {from: address });
    //Backend PHP
    console.log(hash);
    setRefresh(true);
  };

  const payFlag2 = async () => {

    const { address, provider, payment_system_apuntarse, payment_system_casino } = await load();

    let hash = await  payFlagCasino( {from: addressAccount} );
    //Backend PHP
    console.log(hash);
    setRefresh(true);
  };


  return (
    <>
      <Head>
        <title>CTFURJC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul class="nav">
          <li><a href="#">Home</a></li>
          <li><a href="#">Requeriments</a></li>
          <li><a href="#">CTF</a></li>
        </ul>
        <div className="main-box">
          <button onClick={payFlag1} className="button1">First</button>
          <button className="button2">Second</button>
        </div>
      </main>
    </>
  )
}
