import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { load, payFlagApuntarse, payFlagCasino, loadGeneralInformation } from '../functions/functions';
import React, { useState, useEffect } from 'react';

import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [refresh, setRefresh] = useState(true);

  const checkConnection = async () => {

    const { address, provider } = await loadGeneralInformation();
    console.log("Using address: ", address);
    console.log("Using provider: ", provider);
    setRefresh(true);
  
  };
  

  return (
    <>
      <Head>
        <title>CTFURJC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul className={styles.nav}>
        <li><Link href="/">Home</Link></li>
          <li><a href="#">Requeriments</a></li>
          <li><Link href="/payment/payment_system">Payment</Link></li>
          <li><Link href="/code/apuntarseCode">Contrac Apuntarse</Link></li>
          <li><Link href="/code/casinoCode">Contract Casino</Link></li>
          <li><Link href="/documentation/truffle-doc">Truffle Help</Link></li>

        </ul>
        <div>
          <h1>HackOn CTF</h1>
          <div>Bienvenido al reto Blockchain del CTF HackOn</div>

          <div>Mucha suerte con los retos! ^^</div>
          <br />
        
          <hr />
          <br />

          <h2>Requisitos</h2>
          <ul>
          <br />
          
          <h3>Metamask</h3>
          <div>Para poder realizar los retos, es necesario tener instalada la extensión Metamask</div>
          <br />
          
          <h3>Goerli</h3>
          <div>Deberemos tener metamask conectado a la testnet "Goerli"</div>
          <div>ChainID: 5</div>
          <br />
 
          <h4>Como conectar</h4>
          <ul>
            <li>En la parte superior derecha, encontramos un circulo que nos da acceso a la selección de cuentas:</li>
            <li>Vamos a configuración - Avanzando - Mostrar redes de prueba (mitad scroll)</li>
          </ul>
            <div>Seleccionamos Goerli y listo!</div>
          </ul>
          
        </div>
        <div className={styles.mainBox}>
          <button className={styles.button} onClick={checkConnection}>Check Connection</button>
        </div>
      </main>
    </>
  )
}
