import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

export default function truffleDocumentation () {

    return (
        <>
            <Head>
            <title>truffle-help</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
            <ul className={styles.nav}>
                <li><Link href="/">Home</Link></li>
                <li><Link href="/payment/payment_system">Payment</Link></li>
                <li><Link href="/code/apuntarseCode">Contrac Apuntarse</Link></li>
                <li><Link href="/code/casinoCode">Contrac Casino</Link></li>
            </ul>
            <div>
                <br />
                <br />
                <h1>Truffle documentation</h1>
                <br />

                <div>Como interactuar con los contratos utilizando web3 & truffle/hdwallet-provider</div>
                
                <br />
                <br />
                <hr />
                <br />
                <br />

                
                    <h2>Start the project</h2>
                    <br />

                    <div>En primer lugar, deberemos crear un carpeta y abrirla mediante un VSCode</div>
                    <br />
                    <br />


                    <h2>Dependencies</h2>
                    <br />

                    <div>Se necesita tener node.js y una cuenta en algun proveedor de endpoints</div>
                    <br />

                    <div>Se recomienda tener git para utilizar la gitbash</div>

                     <br />
                        
                        <h3>Truffle</h3>
                            <pre>
                                <code>
                                    {`
                                        npm i truffle@latest
                                        npm i @truffle/hdwallet-provider
                                        truffle init 
                                    `}
                                </code>
                            </pre>
                            <br />

                            <div>Deberemos modificar truffle-config.js</div>
                            <br />
                            <div>Configuración de ejemplo: </div>
                            <br />

                            <pre>
                                <code>
                                    {`
                                        const mnemonic = "YOUR_MNEMONIC_PHRASE"; 
                                        const INFURA_API_KEY = 'YOUR_API_KEY';
                                        const HDWalletProvider = require("@truffle/hdwallet-provider");
                                        
                                        module.exports = {
                                        
                                          networks: {
                                            goerli: {
                                              provider: new HDWalletProvider(mnemonic, "https://goerli.infura.io/v3/" + INFURA_API_KEY, 0),
                                        
                                        
                                              network_id: '5', // eslint-disable-line camelcase
                                              gas: 4465030,
                                              gasPrice: 10000000000,
                                            },
                                            
                                          },
                                    `}
                                </code>
                            </pre>


                        <br />
                        <hr />
                        <br />
                        
                        <h3>Web3</h3>
                            <pre>
                                <code>
                                    {`
                                        npm i web3
                                    `}
                                </code>
                            </pre>
                        
                        <br />
                        <hr />
                        <br />
                        
                        <h3>Connection to an endpoint</h3>
                        <br />

                            <div>Para poder interactuar con la cadena, necesitamos tener conexión con un endpoint de la misma.</div>
                            <div>Algunos ejemplos</div>
                            <ul>
                                <li>https://goerli.infura.io/v3/YOUR_API_KEY de Infura</li>
                                <li>https://rpc.ankr.com/eth_goerli de Ankr</li>
                            </ul>

                        <br />
                        <hr />
                        <br />
                        
                        <h3>ABIs</h3>
                            <div>Necesitamos tener la ABI del contrato con el que queremos interactuar.</div>
                        
                        <br />
                        <hr />
                        <br />
                        
                        <h3>Creación del Script</h3>
                            <div>Nos creamos un archivo .js, por ejemplo "interact.js"</div>
                            <pre>
                                <code>
                                    {`
                                        const HDWalletProvider = require("@truffle/hdwallet-provider");
                                        const Web3 = require("web3");
                                        
                                        const contractABI = require("../build/contracts/balance.json").abi;
                                        const contractAdd = "0x...";
                                        
                                        const provider = new HDWalletProvider("YOUR_MNEMONIC_PHRASE", "https://goerli.infura.io/v3/" + "YOUR_API_KEY", 0)
                                        const web3 = new Web3(provider);

                                        async function main() {
                                        
                                            const contract = new web3.eth.Contract(contractABI, "0xa9e385C6E9bE69d1353D05AcA837DadB7EB2ea56");
                                        
                                            const signer = await web3.eth.getAccounts();
                                        
                                            await contract.methods.method_name().call({from: signer[0], gas: 4500000, gasPrice:10000000000 });

                                        }
                                        
                                        main();
                                    `}
                                </code>
                            </pre>
                            <br />

                            <h4>IMPORTANTE</h4>
                            <div>.send se utiliza para las funciones que modifican el estado del contrato</div>
                            <br />

                            <div>.call se utiliza para las funciones que no modifican el estado del contrato</div>


                        <br />
                        <hr />
                        <br />
                        
                        <h4>Contrato Utilizado</h4>
                            <pre>
                                <code>
                                    {`
                                        pragma solidity >=0.8.13;

                                        contract balance {
                                            address public balance;
                                            
                                            constructor () {
                                                balance = 1000;
                                            }
                                            
                                            function getBalance() public view returns (uint256){
                                                return balance;
                                            }
                                        }
                                    `}
                                </code>
                            </pre>
                        <br />
                        <hr />
                        <br />
                        
                        <h3>Llamada al script</h3>
                            <pre>
                                <code>
                                    {`
                                        node interact
                                    `}
                                </code>
                            </pre>

                        <h3>Output</h3>
                            <pre>
                                <code>
                                    {`
                                        node interact
                                        1000
                                    `}
                                </code>
                            </pre>
                
                
                <br />
            </div>
            
    </main>
        </>

        
    )
}
